version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: eb
      POSTGRES_PASSWORD: eb
      POSTGRES_DB: eb
    ports: ["5432:5432"]
  mailhog:
    image: mailhog/mailhog
    ports: ["1025:1025", "8025:8025"]  # 8025 = interface web des mails
